services:
  - type: web
    name: document-converter
    env: python
    buildCommand: "apt-get install -y libreoffice && pip install -r requirements.txt && python manage.py collectstatic --noinput"
    startCommand: "gunicorn core.wsgi --log-file -"
    envVars:
      - key: SECRET_KEY
        sync: false
      - key: DEBUG
        value: false